import { create } from "zustand";

export const useFormStore = create(set => {
    return {
        step: 1,
        animalType: '',
        title: '',
        sizeType: '',
        ageYears: '',
        ageMonths: '',
        sexType: '',
        vaccinated: false,
        unprotected: false,
        castrated: false,
        description: '',
        image: '',
        nombreImagen: '',
        adoptionStatusType: 'FOR_ADOPTION',
        setAnimalType: (newType) => set({ animalType: newType }),
        setNombre: (newNombre) => set({ title: newNombre }),
        setTamanio: (newTamanio) => set({ sizeType: newTamanio }),
        setAnios: (newAnios) => set({ ageYears: newAnios }),
        setMeses: (newMeses) => set({ ageMonths: newMeses }),
        setSexo: (newSexo) => set({ sexType: newSexo }),
        setVacunado: (isChecked) => set({ vaccinated: isChecked }),
        setDesparasitado: (isChecked) => set({ unprotected: isChecked }),
        setCastrado: (isChecked) => set({ castrated: isChecked }),
        setDescripcion: (newDescripcion) => set({ description: newDescripcion }),
        setImagen: (newImagen) => set({ image: newImagen }),
        setNombreImagen: (newNombreImagen) => set({ nombreImagen: newNombreImagen }),
        nextStep: () => set((state) => ({ step: state.step + 1 })),
        prevStep: () => set((state) => ({ step: state.step - 1 })),
        resetForm: () => set(state => ({ 
            animalType: '',
            title: '',
            step: 1,
            sizeType: '',
            ageYears: '',
            ageMonths: '',
            sexType: '',
            vaccinated: false,
            unprotected: false,
            castrated: false,
            description: '',
            image: '',
            nombreImagen: '',
            adoptionStatusType: 'FOR_ADOPTION',
        }))
    }
})
