name: Next.js CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] 

    steps:
      - name: Pull repo
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencias
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
